### ISSUE TITLE
remove drop shadow from inflow (ruins the cut-out effect)

### ISSUE THREAD

**Issue by progrium** [progrium/constructor#4]
<img width="301" alt="Screen Shot 2020-03-19 at 2 24 46 PM" src="https://user-images.githubusercontent.com/647/77106694-85223a80-69ed-11ea-995f-43fb09bb5fdf.png">

**Comment by maxknivets** [comment]
I imagine I could fix it in a few hours.

**Comment by maxknivets** [comment]
Fixed the issue in the recent pull request. Took 4 hours to finish.
