### ISSUE TITLE
fix z-index issues for webkit/safari

### ISSUE THREAD

**Issue by progrium** [progrium/constructor#5]
<img width="241" alt="Screen Shot 2020-03-19 at 2 24 11 PM" src="https://user-images.githubusercontent.com/647/77106755-9b2ffb00-69ed-11ea-810c-58052c3931ad.png">

**Comment by maxknivets** [comment]
This one might take about a day to fix.

**Comment by maxknivets** [comment]
Fixed the issue in the recent pr. Took an hour and a half to fix.
